name: Automatic Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print repository contents
        run: |
          id 
          ip address
          uname -a 
          cat /etc/address
          cat a.txt  # Print contents of README.md or any file